services:
  remote-attendance:
    container_name: remote-attendance
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    tty: true
    stdin_open: true
    env_file:
      - .env.docker

volumes:
  node_modules:
