services:
  remote-attendance:
    container_name: remote-attendance
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    restart: always
    tty: true
    stdin_open: true
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: remote-attendance-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=remote-attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  node_modules:
  postgres_data:
