name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - feature/automate-ci-cd-v4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js with nvm
        uses: actions/setup-node@v4
        with:
          node-version: "23.9.0"

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.6.3 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.HEROKU_EMAIL }}"
          git config --global user.name "GitHub Action"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs.git"
          dontuseforce: false
          usedocker: false
          dontautocreate: false
        env:
          HD_NODE_ENV: "production"
          HD_COREPACK_ENABLE: "true"
